graph TD
NodeSpy1 -->|0<br>Level1| NodeSpy2
NodeSpy1 -->|0<br>Level1| NodeSpy3
NodeSpy2 -->|0<br>Level2| NodeSpy4
NodeSpy2 -->|0<br>Level2| NodeSpy5
NodeSpy3 -->|0<br>Level2| NodeSpy6
NodeSpy3 -->|0<br>Level2| NodeSpy7
NodeSpy4 -->|0<br>Level3| NodeSpy8
NodeSpy4 -->|0<br>Level3| NodeSpy9
NodeSpy5 -->|0<br>Level3| NodeSpy10
NodeSpy5 -->|0<br>Level3| NodeSpy11
NodeSpy6 -->|0<br>Level3| NodeSpy12
NodeSpy6 -->|0<br>Level3| NodeSpy13
NodeSpy7 -->|0<br>Level3| NodeSpy14
NodeSpy7 -->|0<br>Level3| NodeSpy15