graph TD
NodeSpy1 -->|0<br>Level1| NodeSpy2
NodeSpy1 -->|0<br>Level1| NodeSpy3
NodeSpy2 -->|0<br>Level2| NodeSpy4
NodeSpy2 -->|0<br>Level2| NodeSpy5
NodeSpy3 -->|0<br>Level2| NodeSpy6
NodeSpy3 -->|0<br>Level2| NodeSpy7
NodeSpy4 -->|0<br>Level3| NodeSpy5
NodeSpy4 -->|0<br>Level3| NodeSpy8
NodeSpy4 -->|0<br>Level3| NodeSpy9
NodeSpy5 -->|0<br>Level3| NodeSpy10
NodeSpy5 -->|0<br>Level3| NodeSpy11
NodeSpy5 -->|0<br>Level3| NodeSpy6
NodeSpy6 -->|0<br>Level3| NodeSpy12
NodeSpy6 -->|0<br>Level3| NodeSpy13
NodeSpy6 -->|0<br>Level3| NodeSpy7
NodeSpy7 -->|0<br>Level3| NodeSpy14
NodeSpy7 -->|0<br>Level3| NodeSpy15
NodeSpy8 -->|0| NodeSpy9
NodeSpy9 -->|0| NodeSpy10
NodeSpy10 -->|0| NodeSpy11
NodeSpy11 -->|0| NodeSpy12
NodeSpy12 -->|0| NodeSpy13
NodeSpy13 -->|0| NodeSpy14
NodeSpy14 -->|0| NodeSpy15