# .github/workflows/pr-build.yml
name: PR Build & Test

# on:
  # pull_request:
  #   branches: [ main ]          # adjust to your default branch name

on:
  push:
    branches:
      - '**'          # any branch, including your feature branch
  pull_request:
    branches:
    - '**'

  workflow_dispatch:   # ← this line is what makes “Run workflow” appear

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15         # tweak if you need more time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed for coverage tools that use git history

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # matches the sdk version in global.json

      - name: Cache NuGet packages
        uses: actions/cache@v3
        id: nuget-cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Restore NuGet packages
        run: dotnet restore Caravel.sln

      - name: Build solution (Release)
        run: | 
          dotnet build Caravel.sln \
           --configuration Release \
           --no-restore

      - name: Run unit tests
        run: |
          dotnet test ./test/UnitTests/Caravel.Core.UnitTests/Caravel.Core.UnitTests.csproj \
            --configuration Release \
            --no-build 
        continue-on-error: false

      - name: Ensure browsers are installed
        run: |
          pwsh ./examples/PlaywrightDemo/WebSite.PlaywrightTests/bin/Release/net9.0/playwright.ps1 \
            install \
            --with-deps \
            chromium

      - name: Run Playwright tests
        run: |
          dotnet test ./examples/PlaywrightDemo/WebSite.PlaywrightTests/WebSite.PlaywrightTests.csproj \
            --configuration Release \
            --no-build 
        continue-on-error: false

