# .github/workflows/pr-build.yml
name: PR Build & Test

# on:
  # pull_request:
  #   branches: [ main ]          # adjust to your default branch name

on:
  push:
    branches:
      - '**'          # any branch, including your feature branch
  pull_request:
    branches:
    - '**'

  workflow_dispatch:   # ← this line is what makes “Run workflow” appear

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15         # tweak if you need more time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed for coverage tools that use git history

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # matches the sdk version in global.json

      - name: Cache NuGet packages
        uses: actions/cache@v3
        id: nuget-cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Restore NuGet packages
        run: dotnet restore Caravel.sln

      - name: Build solution (Release)
        run: | 
          dotnet build Caravel.sln \
           --configuration Release \
           --no-restore

      - name: Run unit tests
        run: |
          dotnet test ./test/UnitTests/Caravel.Core.UnitTests/Caravel.Core.UnitTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=unit-test-results.trx" \
            --results-directory ${{ github.workspace }}/test-results \
            --collect:"XPlat Code Coverage"
        continue-on-error: false

      - name: Ensure browsers are installed
        run: |
          pwsh ./examples/PlaywrightDemo/WebSite.PlaywrightTests/bin/Release/net9.0/playwright.ps1 \
            install \
            --with-deps \
            chromium

      - name: Run Playwright tests
        run: |
          dotnet test ./examples/PlaywrightDemo/WebSite.PlaywrightTests/WebSite.PlaywrightTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=playwright-test-results.trx" \
            --results-directory ${{ github.workspace }}/test-results \
            --collect:"XPlat Code Coverage"
        continue-on-error: false

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ${{ github.workspace }}/**/test-results/**/*
          retention-days: 1

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"

      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        if: always()
        with:
          reports: "**/*.cobertura.xml"
          targetdir: "${{ github.workspace }}"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          customSettings: "" # See: https://github.com/danielpalme/ReportGenerator/wiki/Settings.
          toolpath: "reportgeneratortool"

      - name: Upload Combined Coverage XML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 1

      - name: Publish Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: always()
        with:
          filename: "Cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "90 100"



